FROM node:20-alpine

WORKDIR /app

# 安装 cnpm（淘宝 npm 镜像）
RUN npm install -g cnpm --registry=https://registry.npmmirror.com

# 只复制依赖文件并安装依赖
COPY package.json /app/
RUN cnpm install --registry=https://registry.npmmirror.com

