FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 只复制依赖文件并安装依赖
COPY pyproject.toml /app/
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir --upgrade pip \
  && pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir .

